using System.Text;
using Monorepo.Tool.IO;

namespace Monorepo.Tool.Generation;

public static class CpmWriter
{
    public static void Write(
        string backendRoot,
        IReadOnlyDictionary<string, string> packageVersions,
        bool dryRun)
    {
        var path    = Path.Combine(backendRoot, "Directory.Packages.props");
        var content = Build(packageVersions);
        AtomicFile.WriteAllTextIfChanged(path, content, dryRun);
    }

    private static string Build(IReadOnlyDictionary<string, string> packageVersions)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<Project>");
        sb.AppendLine("  <!-- Generated by 'monorepo cpm'. Run 'monorepo cpm' to regenerate. -->");
        sb.AppendLine("  <PropertyGroup>");
        sb.AppendLine("    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>");
        sb.AppendLine("  </PropertyGroup>");
        sb.AppendLine("  <ItemGroup>");

        foreach (var (id, version) in packageVersions
            .OrderBy(kv => kv.Key, StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine($"    <PackageVersion Include=\"{id}\" Version=\"{version}\" />");
        }

        sb.AppendLine("  </ItemGroup>");
        sb.AppendLine("</Project>");
        return sb.ToString();
    }
}
