using System.Text.RegularExpressions;
using System.Xml.Linq;
using Monorepo.Tool.Model;

namespace Monorepo.Tool.Generation;

/// <summary>
/// Writes overlay/Directory.Build.props and overlay/Directory.Build.targets.
///
/// The targets file uses a three-layer strategy, all evaluated statically
/// (before NuGet restore) so that project.assets.json is correct from the start:
///
///   Layer 1a — static ItemGroup (evaluation-time, before restore):
///     Snapshot all current PackageReferences into _MonorepoOriginalPackageReference.
///     Must come first so the snapshot is taken before any Remove operations.
///
///   Layer 1b — static ItemGroup (evaluation-time, TFM-gated):
///     Remove every mapped PackageReference so restore never sees them.
///     Skipped for net7.0 / net6.0 / netstandard projects whose TFM is
///     incompatible with the net10.0 source projects — leaving their original
///     PackageReferences in place avoids NU1202 and transitive-version conflicts.
///     Also skipped when $(TargetFramework) is empty (outer multi-targeting build)
///     so each inner build applies its own per-TFM evaluation.
///
///   Layer 2 — static ItemGroups per mapping (evaluation-time, TFM-gated):
///     For each mapped package, check the snapshot and conditionally inject a
///     ProjectReference. Because this runs at evaluation time, the ProjectReference
///     appears in project.assets.json, enabling NuGet to propagate the referenced
///     project's transitive packages (e.g. MediatR, Microsoft.Extensions.*) to
///     the consuming project's compile-time references.
///     Producer guard: the ItemGroup's Condition skips the producing csproj itself.
///     TFM guard:      same condition as Layer 1b — only net8+ projects get the swap.
/// </summary>
public static class OverlayWriter
{
    /// <summary>Item type name used to snapshot @(PackageReference) before removal.</summary>
    private const string SnapshotItemType = "_MonorepoOriginalPackageReference";

    /// <summary>
    /// MSBuild condition fragment that is true only when the consuming project's
    /// TargetFramework is set (i.e. we are in an inner build, not the outer
    /// multi-targeting orchestration build) AND the TFM is compatible with the
    /// net10.0 source projects.  Older TFMs (net7, net6, netstandard) are excluded
    /// so their original PackageReferences are preserved intact.
    /// </summary>
    private const string CompatibleTfmCondition =
        "'$(TargetFramework)' != '' And " +
        "!$([System.String]::Copy('$(TargetFramework)').StartsWith('net7')) And " +
        "!$([System.String]::Copy('$(TargetFramework)').StartsWith('net6')) And " +
        "!$([System.String]::Copy('$(TargetFramework)').StartsWith('netstandard'))";

    public static void Write(
        string                        overlayDir,
        string                        backendRoot,
        IReadOnlyList<PackageMapping> mappings,
        bool                          dryRun = false)
    {
        Directory.CreateDirectory(overlayDir);

        WriteProps(overlayDir, dryRun);
        WriteTargets(overlayDir, backendRoot, mappings, dryRun);
    }

    private static void WriteProps(string overlayDir, bool dryRun)
    {
        // All leaf repos own their own Directory.Build.props so the props walk-up
        // never reaches this file. Generated anyway for future-proofing.
        var doc = new XDocument(
            new XComment(" Auto-generated by 'monorepo'. Do not edit manually. "),
            new XElement("Project"));

        Monorepo.Tool.IO.AtomicFile.WriteAllTextIfChanged(Path.Combine(overlayDir, "Directory.Build.props"), RenderXml(doc), dryRun);
    }

    private static void WriteTargets(
        string                        overlayDir,
        string                        backendRoot,
        IReadOnlyList<PackageMapping> mappings,
        bool                          dryRun)
    {
        var enabled = mappings.Where(m => m.Enabled).ToList();

        // Layer 1a: snapshot element — must come first so the snapshot is taken
        //           before any Remove operations below.  Unconditional: harmless
        //           for all TFMs since it only copies items to a private item type.
        var snapshotItemGroup = new XElement("ItemGroup",
            new XElement(SnapshotItemType,
                new XAttribute("Include", "@(PackageReference)")));

        // Layer 1b: remove all mapped packages — only for compatible TFMs.
        // net7/net6/netstandard projects keep their original PackageReferences
        // because there is no compatible ProjectReference substitute.
        var removeItemGroup = new XElement("ItemGroup",
            new XAttribute("Condition", CompatibleTfmCondition),
            enabled.Select(m =>
                new XElement("PackageReference",
                    new XAttribute("Remove", m.PackageId))));

        // Layer 2: one pair of static ItemGroups per mapping that injects
        //          the ProjectReference at evaluation time (before NuGet restore).
        //          This ensures the ProjectReference is in project.assets.json so
        //          that transitive NuGet packages propagate correctly.
        var rewriteItemGroups = enabled.SelectMany(m => BuildRewriteItemGroups(m, backendRoot, overlayDir));

        var doc = new XDocument(
            new XComment(" Auto-generated by 'monorepo'. Do not edit manually. "),
            new XComment($" {enabled.Count} active mapping(s). "),
            new XElement("Project",
                new XComment(" Layer 1a: snapshot PackageReferences before removal (evaluation-time, before restore). "),
                snapshotItemGroup,
                new XComment(" Layer 1b: remove mapped packages so NuGet restore never sees them (compatible TFMs only). "),
                removeItemGroup,
                new XComment(" Layer 2: statically inject ProjectReferences (evaluation-time, before restore, compatible TFMs only). "),
                rewriteItemGroups));

        Monorepo.Tool.IO.AtomicFile.WriteAllTextIfChanged(Path.Combine(overlayDir, "Directory.Build.targets"), RenderXml(doc), dryRun);
    }

    /// <summary>
    /// Returns two static ItemGroups for a mapping (both evaluated before NuGet restore):
    ///   1. A "had" probe: copies matching items from the snapshot into a helper item type.
    ///   2. A conditional ProjectReference: adds the reference if the probe is non-empty,
    ///      the TFM is compatible (net8+), and this project is not the producer.
    /// Running at evaluation time ensures the ProjectReference lands in project.assets.json
    /// so that the referenced project's transitive NuGet packages propagate correctly.
    /// </summary>
    private static IEnumerable<XElement> BuildRewriteItemGroups(
        PackageMapping mapping, string backendRoot, string overlayDir)
    {
        var safeName = ToSafeName(mapping.PackageId);
        var hadItem  = $"_MonorepoHad_{safeName}";

        var csprojAbs = Path.GetFullPath(
            Path.Combine(backendRoot, mapping.CsprojPath.Replace('/', Path.DirectorySeparatorChar)));
        var csprojRel = Path.GetRelativePath(overlayDir, csprojAbs).Replace('\\', '/');

        var projectRef = $"$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory){csprojRel}'))";

        // Combined condition: probe matched + compatible TFM + not the producer project.
        // XAttribute escapes the double-quote chars to &quot; automatically.
        var producerGuardCondition =
            $"'@({hadItem})' != '' And " +
            CompatibleTfmCondition + " And " +
            $"'$(MSBuildProjectFullPath)' != " +
            $"'$([MSBuild]::NormalizePath(\"$(MSBuildThisFileDirectory){csprojRel}\"))'";

        // ItemGroup 1: probe the snapshot using an item function (no %(metadata) in Condition,
        //              which is disallowed in static evaluation by MSBuild).
        yield return new XElement("ItemGroup",
            new XElement(hadItem,
                new XAttribute("Include",
                    $"@({SnapshotItemType}->WithMetadataValue('Identity', '{mapping.PackageId}'))")));

        // ItemGroup 2: inject ProjectReference if probe matched and not the producer.
        yield return new XElement("ItemGroup",
            new XAttribute("Condition", producerGuardCondition),
            new XElement("ProjectReference",
                new XAttribute("Include", projectRef)));
    }

    private static string ToSafeName(string packageId) =>
        Regex.Replace(packageId, @"[^A-Za-z0-9]", "_");

    private static string RenderXml(XDocument doc)
    {
        using var sw = new StringWriter();
        doc.Save(sw);
        return sw.ToString();
    }
}
