using System.Xml.Linq;
using Monorepo.Tool.IO;

namespace Monorepo.Tool.Generation;

/// <summary>
/// Writes backend/Directory.Build.props and backend/Directory.Build.targets.
/// Each file is a thin sentinel-gated shim that imports the real overlay file.
/// The overlay path is computed from the actual overlay directory so the shim
/// works regardless of layout.
/// </summary>
public static class ShimWriter
{
    public static void Write(string backendRoot, string overlayDir, bool dryRun = false)
    {
        var overlayRelative = Path.GetRelativePath(backendRoot, overlayDir).Replace('\\', '/');

        WriteShim(backendRoot, "Directory.Build.props",   overlayRelative + "/Directory.Build.props",   dryRun);
        WriteShim(backendRoot, "Directory.Build.targets", overlayRelative + "/Directory.Build.targets", dryRun);
    }

    private static void WriteShim(
        string backendRoot,
        string shimFileName,
        string overlayImportPath,
        bool   dryRun)
    {
        var sentinelRef = "$(MSBuildThisFileDirectory).monorepo-active";
        var overlayRef  = $"$(MSBuildThisFileDirectory){overlayImportPath}";

        var doc = new XDocument(
            new XComment(" Auto-generated by 'monorepo'. Do not edit manually. "),
            new XElement("Project",
                new XElement("Import",
                    new XAttribute("Project",   overlayRef),
                    new XAttribute("Condition",
                        $"Exists('{sentinelRef}') and Exists('{overlayRef}')"))));

        var path    = Path.Combine(backendRoot, shimFileName);
        var content = RenderXml(doc);

        AtomicFile.WriteAllTextIfChanged(path, content, dryRun);
    }

    private static string RenderXml(XDocument doc)
    {
        using var sw = new StringWriter();
        doc.Save(sw);
        return sw.ToString();
    }
}
